options:
    base: &base
        dotfileDirectory: test-dotfiles
    
    vimDirectory:
        <<: *base
        directoryName: vim
        links:
            - .vimrc: vimrc

    binDirectory:
        <<: *base
        directoryName: bin
        links:
            - .scripts: bin

    zshDirectory:
        <<: *base
        directoryName: zsh
        links:
            - .zshrc: zshrc
            - .oh-my-zsh/themes/clair.zsh-theme: zsh-theme
